
import type { Metadata } from "next";

import '@/app/globals.css'

import { NextIntlClientProvider, hasLocale } from 'next-intl';
import { notFound } from 'next/navigation';
import { routing } from '@/i18n/routing';
import AppWrapper from "./AppWrapper";
import Provider from "@/lib/provider";
export const metadata: Metadata = {
  title: "AriMayi",
  description: "Generated by create next app",
};




export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode,
  params: Promise<{ locale: string }>
}>) {
  // Ensure that the incoming `locale` is valid
  const { locale } = (await params);

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }



  return (
    <html lang={locale}>
      <Provider>
        <NextIntlClientProvider>
          <AppWrapper>
    {children}
          </AppWrapper>
        </NextIntlClientProvider>
      </Provider>
    </html >
  );
}
